[package]
name = "state_manipulation"
version = "0.1.0"
authors = ["Ryan1729 <Ryan1729@gmail.com>"]

[lib]
crate-type = ["dylib"]

[dependencies]
rand = "0.3"

[dependencies.common]
path = "../common"
